# Generated by Django 5.0.3 on 2024-05-20 08:05

import django.utils.timezone
import tourList.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('pay_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('is_confirmed', models.BooleanField()),
                ('bank_account_no', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('review', models.CharField(max_length=1000)),
                ('review_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SavedPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TourItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img_path', models.ImageField(blank=True, null=True, upload_to=tourList.models.upload_path_item)),
                ('duration', models.DecimalField(decimal_places=2, max_digits=3)),
                ('price', models.IntegerField()),
                ('level', models.IntegerField()),
                ('description', models.CharField(max_length=2000)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TourList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('duration', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('recommended_people_no', models.IntegerField(default=1)),
                ('type', models.CharField(max_length=20)),
                ('tag1', models.CharField(max_length=30)),
                ('tag2', models.CharField(max_length=30)),
                ('tag3', models.CharField(max_length=30)),
                ('province', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=2000)),
                ('main_img_path', models.ImageField(blank=True, null=True, upload_to=tourList.models.upload_path)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
