# Generated by Django 5.0.3 on 2024-05-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('data_type', models.CharField(max_length=10)),
                ('value', models.CharField(max_length=20)),
            ],
            options={
                'unique_together': {('group_name', 'name')},
            },
        ),
    ]
