# Generated by Django 5.0.3 on 2024-05-20 08:18

from django.db import migrations

def add_constants(apps, schema_editor):
    Constants = apps.get_model("user","Constants")
    Constants.objects.bulk_create([
        Constants(group_name='data_type_grp', name='text', data_type='text', value='text'),
        Constants(group_name='data_type_grp', name='number', data_type='text', value='number'),
        Constants(group_name='data_type_grp', name='date', data_type='text', value='date'),
    ])
class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_constants'),
    ]

    operations = [
        migrations.RunPython(add_constants)
    ]
